### ISSUE TITLE
FeedManager is not documented well in relation to InAppFeedView

### ISSUE THREAD

**Issue by jdhiro** [knocklabs/knock-swift#11]
I spent hours struggling with the KnockInAppFeedView.

I carefully followed the documentation...
here: https://docs.knock.app/in-app-ui/ios/components#examples-1
```swift
@EnvironmentObject var viewModel: Knock.InAppFeedViewModel = .init()
KnockInAppFeedView(theme: KnockInAppFeedTheme(titleString: "Notifications"))
    .environmentObject(viewModel)
    .onReceive(viewModel.didTapFeedItemButtonPublisher) { actionString in
        print("Button with action \(actionString) was tapped.")
    }
    .onReceive(viewModel.didTapFeedItemRowPublisher) { item in
        print("Row item was tapped")
    }`
```

and here: https://docs.knock.app/sdks/ios/reference#examples
```swift
@State var viewModel = Knock.InAppFeedViewModel()
let feedView = Knock.InAppFeedView().environmentObject(viewModel)
```

No matter what I did, the feed loaded empty, and changing states led to a spinner icon.

After spending the day closely inspecting the demo app, I found this line:
```swift
Knock.shared.feedManager = try? await Knock.FeedManager(feedId: "<example feed id>")
```

I tossed this into my AppDelegate and then everything worked.

It's not clear what the specific relationship is to FeedManager for the view, and I wouldn't have known this without digging through the demo app. I think this really should be made easier, or more clear in the docs.

**Comment by matgar26** [comment]
@jdhiro Thanks for the feedback. I think you are right and that this needs to be made more clear. We will get that documentation updated.
